---
- name: Update Webserver
  hosts: group1
  become: yes
  vars:
    httpd_port: 80

  handlers:
  - name: Restart apache
    service:
      name: httpd 
      state: restarted

  tasks:
  - name:
    selinux:
      policy: targeted 
      state: permissive
  - name:
    template:
      src: httpd.j2 
      dest: /etc/httpd/conf/httpd.conf
    notify:
    - Restart apache

...
