---
  - name: Ensure httpd is installed
    package:
      name: httpd
      state: present
  - name: Ensure httpd is started
    service:
      name: httpd
      state: started
  - name: Ensure httpd is enabled
    service:
      name: httpd
      enabled: yes
...
